root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/web_app"
  cmd = "go build -o ./tmp/web_app server/main.go"
  delay = 0
  full_bin = ""
  include_dir = ["content", "static", "server"]
  include_ext = ["go", "html", "md", "toml"]
  include_file = ["template.html", ".air.toml"]
  exclude_dir = [""]
  exclude_file = []
  exclude_regex = ["_test\\.go"]
  exclude_unchanged = false
  follow_symlink = false
  kill_delay = "0s"
  log = "air.log"
  poll = false
  poll_interval = 500 # ms
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true
