app = 'lxkota'
primary_region = 'ewr'

[build]
  dockerfile = "build/Dockerfile"
  [build.args]
    GO_VERSION = '1.23.1'

[env]
  PORT = '42069'

[http_service]
  internal_port = 42069
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
